### PR TITLE
Update airgeddon.sh

### PR DESCRIPTION
**Pull request by zartaz**
in latest kali print $1 shows mode

### CODE REVIEW

**Comment by OscarAkaElvis** [comment]
Hi, sorry but we don't accept pull requests to our master branch. Check our git workflow policy on contributing section.

Anyway, checking your suggested changes, I guess that something has changed in some package. Which one? If iwconfig is affected probably it will be wireless-tools package. airgeddon is able to work with versions 29 and 30. I'll check if a new release arrived to the repos and I'll do the needed changes if they are finally needed. Bear in mind that we are compatible to a lot of Linux and versions. Accepting this PR will cause other linux to don't work correctly. The proper modification of this in the case that something changed on iwconfig output is to detect the wireless-tools version and modify the command line based on that. Or maybe this is caused in your case due a custom driver which is not printing output in the right place (we saw cases of that with some drivers on some chipsets like RTL8812AU).

I'll update to the latest my Kali vm and I'll check closely.

**Comment by zartaz** [comment]
Thanks for replying, you are right, i use rtl8812au,i"ll try to edit the
script to be compatible with this adapter

Στις Δευ, 21 Οκτ 2019, 16:11 ο χρήστης Óscar Alfonso Díaz <
notifications@github.com> έγραψε:

**Comment by OscarAkaElvis** [comment]
Don't do that. This is something that we already discussed many times. RTL8812AU has drivers that are not following the standards. And we are not interested in modifications that are not following the standards. So even with a modification that could co-exist with normal cards and this cursed card, we don't want to perform "dirty" modifications in our code just for one card model, so don't waste efforts.

Anyway, we have planned to address this using the new feature: plugins system. With it, we'll be able to address the problem of this chipset without doing "dirty" stuff inside airgeddon. Read this carefully, we have a section talking about what you need. https://github.com/v1s1t0r1sh3r3/airgeddon/issues/308

**Comment by zartaz** [comment]
Thanks mate , i'll read that

Στις Δευ, 21 Οκτ 2019, 16:45 ο χρήστης Óscar Alfonso Díaz <
notifications@github.com> έγραψε:

**Pull request closed without merging**
