### PR TITLE
Update italian language

### PR DESCRIPTION
**Pull request by zonalimitatore**
Update italian language

### CODE REVIEW

**Comment by OscarAkaElvis** [comment]
Also breaking indentation

image

Sorry but you need to be very meticulous to collaborate in airgeddon. Fix every single space or broken tab or it will be rejected. If you are modifying italian strings, you must be modifying ONLY that... no spaces, no tabs and of course, no other language strings.

Now you need to be very accurate on your next commit to fix everything to their initial state but italian strings or it will be rejected. We are not here to fix other users' lack of attention.

**Comment by zonalimitatore** [comment]
I didn't change anything except the Italian language. I took the file directly from the dev section. I had done and tested work up to 1.30. In 1.40 there were only 2 more lines to change, nothing more.

**Comment by OscarAkaElvis** [comment]
I think you are not realizing about what happened here. I'll try to explain it for you.

1. You forked the repo and get the dev branch
2. While you have your forked repo, airgeddon original repo changed... some language strings like string et_misc_texts 28 changed from "Portal access" to "Portal accessed" in all languages and probably others.
3. You modify your stuff in your obsolete version without updating it with the original repo's new content
4. You do a PR and the result is this and my comment is because of that.

The proof is simple. Check what string et_misc_texts 28 contains in your repo and check what is in the airgeddon's dev branch... it is different. Now if you try to put your stuff on dev, you are overwritting some strings and that is the cause that you are modifying other languages, the lack of updating... so or you fix all the stuff you are breaking doing another commit or we must reject the PR, sorry. You should get airgeddon's dev language string file and your file and do a diff... get the differences... and all modified stuff different than the italian strings is an error.

If you don't know how to fix this because you are not skilled using git, you can close the PR and fork again, update, do your stuff again and do PR again... but is a lot of work. I think that git stuff is better to learn... so check over the internet about how to fix that stuff using git commands.

**Comment by zonalimitatore** [comment]
I've this: 
	et_misc_texts["ENGLISH",28]="Portal access"
	et_misc_texts["SPANISH",28]="Acceso al portal"
	et_misc_texts["FRENCH",28]="\${pending_of_translation} Accès au portail"
	et_misc_texts["CATALAN",28]="\${pending_of_translation} Accés al portal"
	et_misc_texts["PORTUGUESE",28]="\${pending_of_translation} Acesso ao portal"
	et_misc_texts["RUSSIAN",28]="\${pending_of_translation} Доступ к порталу"
	et_misc_texts["GREEK",28]="\${pending_of_translation} Πρόσβαση στην πύλη"
	et_misc_texts["ITALIAN",28]="\${pending_of_translation} Accesso al portale"
	et_misc_texts["POLISH",28]="\${pending_of_translation} Dostęp do portalu"
	et_misc_texts["GERMAN",28]="\${pending_of_translation} Portalzugang"
	et_misc_texts["TURKISH",28]="\${pending_of_translation} Portal erişimi"
	et_misc_texts["ARABIC",28]="\${pending_of_translation} الوصول إلى البوابة"
	et_misc_texts["CHINESE",28]="\${pending_of_translation} 门户访问"

**Comment by zonalimitatore** [comment]
https://github.com/v1s1t0r1sh3r3/airgeddon/pull/619/commits/6b0fd15b9e24d6ebffbf8d1f8ed5fd174afc0a8a
This solve

**Pull request closed without merging**
