### PR TITLE
WIP: handshake detecting

### PR DESCRIPTION
**Pull request by IwraStudios**
(WIP) Pull request for #136

### TODO

* Test the current changes
* Remove ${yesno} check

### CODE REVIEW

**Comment by OscarAkaElvis** [comment]
Hi, here I can see two problems...

First is that the temporary file with the content of airodump should be at the tmp dir... so you should use the ${tmp} var after the redirection ">" , and the name of the file could be in a var defined at the beginning (choose a name... for example "tmpairodump_file". It could be something like `> "${tmpdir}${tmpairodump_file}"` for example at the end of the airodump command.

On the other hand... instead of `grep -q handshake` you should use some kind of regular expression. Because as it is now, if for example you detect a wireless network called handshake... it will detect as you have the handshake, and that's not true... so a fine tunning should be done on this part to try to detect the WPA handshake as better as possible.

I'm going to accept it but you should bear in mind this changes after the PR accept. Thanks.

**Comment by IwraStudios** [comment]
@OscarAkaElvis As airodump uses bssid's (which are always hex) the likelihood that a duplicate of handshake or WPA comes in the screen is unlikely

**Comment by OscarAkaElvis** [comment]
Yeah, I mean that the string to search should be something more than "handshake". Here you have a screenshot of how appear:

image

I guess you'll be able to do it, for sure 😄

**Comment by IwraStudios** [comment]
Ah I see now,  I guess my screen is to small for it to display that

**Pull request merged**
