### PR TITLE
update airgeddon.sh - precheck for mac_spoofing_desired in et_prerequisites()

### PR DESCRIPTION
**Pull request by Bogdan107**
Patch allows to simplify the code of an external plugin.
Relevant for spoof_mac_automatically  plugin (https://github.com/Bogdan107/airgeddon_plugins/blob/main/spoof_mac_automatically.sh).

Currently the "spoof_mac_automatically" plugin needs to override the "et_prerequisites" function, which contains about 200 lines of code.
With this patch, an external plugin can silently suppress the MAC spoofing request in  prehook of "et_prerequisites" without copying 200 lines of code.

**Why do I need this** if the plugin can use the override function?
Any changes to the code of the original "et_prerequisites" function increase the distance between the plugin code and the original code.
In future updates, if the et_prerequisites function code changes, the plugin must also be updated.
Thus, I needs sometimes to keep track code of the et_prerequisites function and update the code of plugin.
With this patch, the external plugin does not need to be synchronized with the original et_prerequisites function.

### CODE REVIEW

**Review by Bogdan107 — COMMENTED** [review]
Ask the user to change the MAC address only if one of the following conditions is met:
- the variable mac_spoofing_desired does not exist;
- the mac_spoofing_desired variable has a value of 0, which set in the restore_et_interface() function.

**Comment by OscarAkaElvis** [comment]
Hi, I saw at first sight you did the PR to our master branch which is not allowed. It seems then you corrected it, so ok about that.

Regarding modification, I'm doing some tests with the required change in order to be sure that anything is broken... it seems with your modifications, the default behavior of airgeddon doesn't change (and because of this, probably it'll be accepted). Anyway, is not our style to modify airgeddon to ease plugins tasks but I can understand your point. To accept it, more stuff must happen:

1. Default behavior of airgeddon must not change <- i'm testing it and it seems this is ok
2. I need to like your plugin <- i'm testing it and it works fine
3. Need to check the final result. Can you provide a version of the plugin using the posthook instead of overrride to see the final result? I'll test it using your PR airgeddon version. Maybe a good aproach for this could be to create a branch on your plugin repo with that changes, and after this PR if finally merged, you can also merge your new plugin branch to your master branch on your plugin repo.

One last thing, not relevant for this but I think you missed it. It seems you missed the restore for the bully pixiewps attack and also for the custom pin reaver and custom pin bully attacks (3 in total).

**Comment by Bogdan107** [comment]
Worked plugin before pull #452 - commit [41271a3](https://github.com/Bogdan107/airgeddon_plugins/commit/41271a3c15826e2876b3015796a5f9f3e25e7067)

Worked plugin after pull #452 - commit [692a3fd](https://github.com/Bogdan107/airgeddon_plugins/commit/692a3fd0beefd640f91ede2f465cb07205f85ceb)

**Comment by Bogdan107** [comment]
Posthooks for missed attacks added in commit [ae79ef7](https://github.com/Bogdan107/airgeddon_plugins/commit/ae79ef79d4860c0448065b20d420fecb05ebe525)

**Comment by OscarAkaElvis** [comment]
> Posthooks for missed attacks added in commit [ae79ef7](https://github.com/Bogdan107/airgeddon_plugins/commit/ae79ef79d4860c0448065b20d420fecb05ebe525)

Maybe you also should add `plugin_minimum_ag_affected_version=10.42` on your plugin <- is the version where these changes will be available (this PR).

**Review by Bogdan107 — COMMENTED** [review]
Bug in comparsion of literal is fixed

**Comment by Bogdan107** [comment]
> Maybe you also should add `plugin_minimum_ag_affected_version=10.42` on your plugin

Minimum airgeddon version uplevel to 10.42 in [63c98cc](https://github.com/Bogdan107/airgeddon_plugins/commit/63c98cceb6fcac36d39683565d727ba5775da7a9)

**Pull request merged**
